import type { Metadata } from "next";
import "./globals.css";
import Navbar from '@/components/NavBar'; // Import the updated Navbar

export const metadata: Metadata = {
  title: "SnapZoska",
  description: "Generated by students of SPSE Zochova 9, Bratislava",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sk">
      <body>
        <div style={{ paddingBottom: '56px' }}> {/* Ensure content does not overlap the navbar */}
          {children} {/* Render page content */}
        </div>
        <Navbar />  {/* Navbar at the bottom */}
      </body>
    </html>
  );
}
