import type { Metadata } from "next";
import "./globals.css";
import Navbar from '/home/maximiliankiss@s.zochova.sk/Dokumenty/Dev/moje/src/components/NavBar.tsx'; // Import the Navbar component

export const metadata: Metadata = {
  title: "SnapZoska",
  description: "Generated by students of SPSE Zochova 9, Bratislava",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sk">
      <body>
        <Navbar />  {/* Navbar will be rendered on top */}
        {children}  {/* Render the children components */}
      </body>
    </html>
  );
}
